FROM eclipse-temurin:17
LABEL mentainer="khoahoangyahoo@gmail.com"
WORKDIR /app
COPY target/source-backend-0.0.1-SNAPSHOT.jar /app/spring-ecommerce.jar
ENTRYPOINT ["java", "-jar", "spring-ecommerce.jar"]